num_epochs: 500
working_folder: experiments/initial
patch_shape: [12, 256, 256]

model:
 type: UNet
 start_iblock_channels: 32
 num_down_blocks: 4
 layers_per_block: 4

optimizer:
 lr: 5e-5

data:
 train_image_path: data/images/mito_h_train.tiff
 train_label_path: data/labels/mito_h_train.tiff
 val_image_path: data/images/mito_h_val.tiff
 val_label_path: data/labels/mito_h_val.tiff
 batch_size: 4
 steps_per_train_epoch: 100
 steps_per_val_epoch: 10
